# Generated by Django 4.0.4 on 2022-05-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0002_alter_news_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
    ]
